version: "2"
run:
  go: "1.23"
linters:
  enable:
    - misspell
    - revive
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - clipnest
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
